services:
  - type: web
    name: infobait
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: COHERE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.6"
